steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
      'build', 
      '-t', 
      'asia-south1-docker.pkg.dev/merapashu360-buyer-app/cloud-run-source-deploy/mera-maps', 
      '--build-arg',
      'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyBg9ZxwT8cpJJOQA-LiJ-Pi24-3rhsN0OU',
      '--build-arg',
      'NEXT_PUBLIC_GOOGLE_MAP_ID=68b8f843e24917af',

      '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/merapashu360-buyer-app/cloud-run-source-deploy/mera-maps']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 
      'deploy', 
      'mera-maps', 
      '--image', 
      'asia-south1-docker.pkg.dev/merapashu360-buyer-app/cloud-run-source-deploy/mera-maps', 
      '--env-vars-file',
      'prod-env.yaml',
      '--region', 
      'asia-south1'
      ]
options:
  logging: CLOUD_LOGGING_ONLY